name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # This cron expression runs the job at midnight (00:00) UTC every day.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Evidence Project
        env:
          # This automatically uses your repo name to set the base path
          BASE_PATH: '/${{ github.event.repository.name }}'
          
          # Load the secret into an intermediary env var
          GCP_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
          
          # Tell the Google Cloud client library where to find the credentials file
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-credentials.json
        run: |
          # Write the credentials from the env var into the file.
          # The double quotes are critical to preserve the multi-line JSON structure.
          echo "$GCP_SA_KEY" > $GOOGLE_APPLICATION_CREDENTIALS
          
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # This path must match your build directory from package.json
          path: 'build/${{ github.event.repository.name }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4