name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # This cron expression runs the job at midnight (00:00) UTC every day.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Evidence Project
        env:
          # This automatically uses your repo name to set the base path
          BASE_PATH: '/${{ github.event.repository.name }}'

          # Your BigQuery Service Account credentials.
          # These are not secrets and are needed for the connection
          EVIDENCE_SOURCE__spoti__authenticator: service-account
          EVIDENCE_SOURCE__spoti__location: EU
          # These are parsed from the single GCP_CREDENTIALS secret
          EVIDENCE_SOURCE__spoti__PROJECT_ID: ${{ fromJson(secrets.GCP_CREDENTIALS).project_id }}
          EVIDENCE_SOURCE__spoti__CLIENT_EMAIL: ${{ fromJson(secrets.GCP_CREDENTIALS).client_email }}
          EVIDENCE_SOURCE__spoti__PRIVATE_KEY: ${{ fromJson(secrets.GCP_CREDENTIALS).private_key }}

        run: |
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # This path must match your build directory from package.json
          path: 'build/${{ github.event.repository.name }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4