name: Sync Starred GitHub Repositories

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: "0 8 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  sync-starred-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run starred repos sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_SHEET_NAME: ${{ vars.GOOGLE_SHEET_NAME || 'StarredRepos' }}
        run: |
          python scripts/starred_repos_fetcher.py

      - name: Report status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Starred repos sync completed successfully"
          else
            echo "❌ Starred repos sync failed"
            exit 1
          fi